"""
Django settings for cns_app project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

try:
    import dj_database_url
except ImportError:  # pragma: no cover - optional until deployment deps are installed
    dj_database_url = None

try:
    import whitenoise  # noqa: F401
except ImportError:  # pragma: no cover - optional until deployment deps are installed
    whitenoise = None

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env", override=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "SECRET_KEY", "django-insecure-3+i7&y5z628g^d@c=uq#rdsj^y8_20z22l0418e4i0j+87b#qf"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False").strip().lower() == "true"

ALLOWED_HOSTS = [
    host.strip() for host in os.getenv("ALLOWED_HOSTS", "").split(",") if host.strip()
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Local
    "outreach",
    # Third-party
    "django_celery_results",
]

LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "login"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

if whitenoise:
    MIDDLEWARE.insert(1, "whitenoise.middleware.WhiteNoiseMiddleware")

ROOT_URLCONF = "cns_app.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "cns_app.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if dj_database_url:
    DATABASES = {
        "default": dj_database_url.config(
            default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
            conn_max_age=600,
        )
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
if whitenoise:
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ---------------------------------------------------------------------------
# Email (SMTP)
# ---------------------------------------------------------------------------
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", 587))
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER)
OUTREACH_CC_EMAILS = os.getenv("OUTREACH_CC_EMAILS", "")  # comma-separated

# ---------------------------------------------------------------------------
# Google Gemini AI
# ---------------------------------------------------------------------------
GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY", "")
GEMINI_MODEL = os.getenv("GEMINI_MODEL", "gemini-2.5-flash")

# How many corrective re-generations to attempt when a draft fails the content
# quality gate (outreach/quality.py) — e.g. it came back with the sample
# email's "[Company]" / "[specific domain]" placeholders left unfilled.
# Each repair costs one extra Gemini call and only runs on drafts that would
# otherwise be unsendable. Set to 0 to disable repair (a failed draft then
# falls straight through to the safe static template).
AI_MAX_REPAIR_ATTEMPTS = int(os.getenv("AI_MAX_REPAIR_ATTEMPTS", "1"))

# Google-Search-grounded company research is cached per company rather than
# re-run per contact. A successful summary is reused for this many days; an
# empty one is retried much sooner, since an empty result is usually transient
# and reusing it would lock a company into permanently generic emails.
RESEARCH_CACHE_TTL_DAYS = int(os.getenv("RESEARCH_CACHE_TTL_DAYS", "30"))
RESEARCH_EMPTY_RETRY_HOURS = int(os.getenv("RESEARCH_EMPTY_RETRY_HOURS", "6"))

# ---------------------------------------------------------------------------
# IMAP (for scanning replies)
# ---------------------------------------------------------------------------
IMAP_HOST = os.getenv("IMAP_HOST", "imap.gmail.com")
IMAP_PORT = int(os.getenv("IMAP_PORT", "993"))

# ---------------------------------------------------------------------------
# Follow-up settings
# ---------------------------------------------------------------------------
FOLLOWUP_INTERVALS_DAYS = [3, 7, 14]  # days between each follow-up round
MAX_FOLLOWUPS = 3

# Username of the TeamMember whose mailbox unattended, Celery-Beat-triggered
# follow-ups/reply-scans send/scan from (there's no interactive "triggering
# user" for a scheduled run to resolve credentials from otherwise).
AUTOMATED_SENDER_USERNAME = os.getenv("AUTOMATED_SENDER_USERNAME", "")

# ---------------------------------------------------------------------------
# Field-level encryption (TeamMember.mailbox_app_password at rest)
# ---------------------------------------------------------------------------
ENCRYPTION_KEY = os.getenv("ENCRYPTION_KEY", "")
if not ENCRYPTION_KEY and not DEBUG:
    raise ImproperlyConfigured(
        "ENCRYPTION_KEY must be set in production — generate one with: "
        "python -c \"from cryptography.fernet import Fernet; "
        "print(Fernet.generate_key().decode())\""
    )

# ---------------------------------------------------------------------------
# Error tracking (optional, free tier — no-op unless SENTRY_DSN is set)
# ---------------------------------------------------------------------------
SENTRY_DSN = os.getenv("SENTRY_DSN", "")
if SENTRY_DSN:
    import sentry_sdk
    from sentry_sdk.integrations.celery import CeleryIntegration
    from sentry_sdk.integrations.django import DjangoIntegration

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[DjangoIntegration(), CeleryIntegration()],
        traces_sample_rate=0.0,
    )


# ---------------------------------------------------------------------------
# Celery
# ---------------------------------------------------------------------------
# Default broker: Redis. If Redis is not available locally (no Docker),
# set CELERY_BROKER_URL=filesystem:// in .env to use the filesystem transport
# (development only — no external service required).
_broker_url = os.getenv("CELERY_BROKER_URL", "redis://localhost:6379/0")
CELERY_BROKER_URL = _broker_url

# Filesystem broker transport options (only used when broker is filesystem://)
CELERY_BROKER_TRANSPORT_OPTIONS = {
    "data_folder_in": str(BASE_DIR / "celery_broker"),
    "data_folder_out": str(BASE_DIR / "celery_broker"),
}

CELERY_RESULT_BACKEND = "django-db"  # stores results in django_celery_results
CELERY_CACHE_BACKEND = "default"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True

# Deliberately NOT tied to DEBUG: a staging/demo deployment left in DEBUG=True
# used to silently run tasks synchronously with zero rate limiting between
# sends (see the time.sleep(2) guard in tasks.py), hammering Gemini/SMTP.
# Set this explicitly via env var for local dev without a worker running.
CELERY_TASK_ALWAYS_EAGER = os.getenv("CELERY_TASK_ALWAYS_EAGER", "False").strip().lower() == "true"
CELERY_TASK_EAGER_PROPAGATES = CELERY_TASK_ALWAYS_EAGER

# A worker that dies mid-task redelivers the task instead of losing it —
# safe because the atomic per-client claim in tasks.py makes reprocessing
# idempotent (a client already claimed by the crashed attempt just gets
# skipped by the retry, per _claim_client's compare-and-swap).
CELERY_TASK_ACKS_LATE = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1

# Genuinely unattended follow-ups/reply-scans (the product's own "automated
# follow-up sequences" claim) — requires AUTOMATED_SENDER_USERNAME to be set
# to a TeamMember whose mailbox these scheduled runs should send/scan from,
# and a live Celery worker + beat process. Adjust cadence to taste.
from celery.schedules import crontab  # noqa: E402

CELERY_BEAT_SCHEDULE = {
    "send-followups-periodic": {
        "task": "outreach.send_followups",
        "schedule": crontab(minute=0, hour="*/6"),
    },
    "scan-inbox-periodic": {
        "task": "outreach.scan_inbox_for_replies",
        "schedule": crontab(minute=0, hour="*/2"),
    },
    "reconcile-stuck-runs": {
        "task": "outreach.reconcile_stuck_runs",
        "schedule": crontab(minute="*/15"),
    },
}

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
# Previously absent entirely — outreach/tasks.py's logger.info/warning/error
# calls throughout Gemini/SMTP/IMAP error handling only reached Django's
# default (console-only, level-WARNING-ish) config. Explicit here so the
# outreach app's INFO-level detail (Gemini fallbacks, SMTP retries) is
# actually emitted, wherever the deployment platform captures stdout/stderr.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{asctime} {levelname} {name}: {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "WARNING",
    },
    "loggers": {
        "outreach": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "django": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
    },
}
