# Generated by Django 5.2.1 on 2026-03-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outreach", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="client",
            name="country",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="client",
            name="keywords",
            field=models.TextField(
                blank=True, help_text="Comma-separated tags from Apollo"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="linkedin_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="client",
            name="phone",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="client",
            name="state",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="client",
            name="title",
            field=models.CharField(
                blank=True, help_text="Job title, e.g. CEO, Founder", max_length=150
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="website",
            field=models.URLField(blank=True),
        ),
    ]
