# Generated by Django 5.2.1 on 2026-03-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outreach", "0002_client_city_client_country_client_keywords_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CampaignRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("total", models.PositiveIntegerField(default=0)),
                ("processed", models.PositiveIntegerField(default=0)),
                ("sent", models.PositiveIntegerField(default=0)),
                ("failed", models.PositiveIntegerField(default=0)),
                ("current_company", models.CharField(blank=True, max_length=255)),
                (
                    "current_step",
                    models.CharField(
                        blank=True,
                        help_text="researching / generating / sending",
                        max_length=50,
                    ),
                ),
                ("log", models.JSONField(blank=True, default=list)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
    ]
