# Generated by Django 5.2.1 on 2026-03-09 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outreach", "0003_campaignrun"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="followup_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="client",
            name="has_replied",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="client",
            name="last_reply_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="next_followup_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="reply_snippet",
            field=models.TextField(blank=True, help_text="Preview of latest reply"),
        ),
        migrations.AddField(
            model_name="client",
            name="sentiment",
            field=models.CharField(
                choices=[
                    ("Unknown", "Unknown"),
                    ("Positive", "Positive"),
                    ("Interested", "Interested"),
                    ("Neutral", "Neutral"),
                    ("Negative", "Negative"),
                    ("Not Interested", "Not Interested"),
                ],
                default="Unknown",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="status",
            field=models.CharField(
                choices=[
                    ("Not Contacted", "Not Contacted"),
                    ("Pinged", "Pinged"),
                    ("Replied", "Replied"),
                    ("Follow Up", "Follow Up"),
                    ("Meeting Set", "Meeting Set"),
                    ("Rejected", "Rejected"),
                ],
                default="Not Contacted",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="EmailReply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=500)),
                ("body", models.TextField()),
                ("received_at", models.DateTimeField()),
                (
                    "sentiment",
                    models.CharField(
                        choices=[
                            ("Unknown", "Unknown"),
                            ("Positive", "Positive"),
                            ("Interested", "Interested"),
                            ("Neutral", "Neutral"),
                            ("Negative", "Negative"),
                            ("Not Interested", "Not Interested"),
                        ],
                        default="Unknown",
                        max_length=20,
                    ),
                ),
                (
                    "sentiment_summary",
                    models.TextField(
                        blank=True, help_text="AI-generated sentiment explanation"
                    ),
                ),
                (
                    "message_id",
                    models.CharField(
                        help_text="Email Message-ID for deduplication",
                        max_length=500,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="outreach.client",
                    ),
                ),
            ],
            options={
                "ordering": ["-received_at"],
            },
        ),
    ]
