# Generated by Django 5.2.1 on 2026-03-10 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outreach", "0005_teammember"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                help_text="Team member responsible for this client. Null = shared pool.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_clients",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
