# Generated by Django 5.2.1 on 2026-03-15 16:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outreach", "0006_client_assigned_to"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LinkedInReachout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reachout_type",
                    models.CharField(
                        choices=[
                            ("Connection Request", "Connection Request"),
                            ("Direct Message", "Direct Message"),
                            ("InMail", "InMail"),
                            ("Follow-up", "Follow-up"),
                            ("Other", "Other"),
                        ],
                        default="Direct Message",
                        max_length=30,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "happened_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linkedin_reachouts",
                        to="outreach.client",
                    ),
                ),
                (
                    "team_member",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="linkedin_reachouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-happened_at", "-created_at"],
            },
        ),
    ]
