# Generated by Django 6.0.3 on 2026-03-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outreach", "0007_linkedinreachout"),
    ]

    operations = [
        migrations.AddField(
            model_name="teammember",
            name="mailbox_app_password",
            field=models.CharField(
                blank=True,
                help_text="App password or mailbox password used for SMTP/IMAP.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="teammember",
            name="mailbox_email",
            field=models.EmailField(
                blank=True,
                help_text="Mailbox used for outbound email and IMAP reply scanning.",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="teammember",
            name="sender_name",
            field=models.CharField(
                blank=True,
                help_text="Name shown in outbound outreach emails.",
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="teammember",
            name="sender_role",
            field=models.CharField(
                blank=True,
                help_text="Role/title shown in the email signature.",
                max_length=150,
            ),
        ),
    ]
