# Generated by Django 6.0.3 on 2026-08-31 10:38

import django.core.validators
import django.db.models.deletion
import outreach.fields
from django.conf import settings
from django.db import migrations, models


def populate_audit_snapshots_and_encrypt_credentials(apps, schema_editor):
    ActionLog = apps.get_model("outreach", "ActionLog")
    EmailReply = apps.get_model("outreach", "EmailReply")
    TeamMember = apps.get_model("outreach", "TeamMember")

    for entry in ActionLog.objects.select_related("client").iterator():
        if entry.client_id:
            entry.client_company = entry.client.company_name
            entry.client_email = entry.client.email
            entry.save(update_fields=["client_company", "client_email"])

    for reply in EmailReply.objects.select_related("client").iterator():
        if reply.client_id:
            reply.client_company = reply.client.company_name
            reply.client_email = reply.client.email
            reply.save(update_fields=["client_company", "client_email"])

    # Reading supports legacy plaintext; saving through the new field encrypts it.
    for profile in TeamMember.objects.exclude(mailbox_app_password="").iterator():
        profile.mailbox_app_password = profile.mailbox_app_password
        profile.save(update_fields=["mailbox_app_password"])


class Migration(migrations.Migration):

    dependencies = [
        ("outreach", "0008_teammember_mailbox_app_password_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="actionlog",
            name="client_company",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="actionlog",
            name="client_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="campaignrun",
            name="campaign",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="runs",
                to="outreach.outreachcampaign",
            ),
        ),
        migrations.AddField(
            model_name="campaignrun",
            name="error_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="campaignrun",
            name="fallback_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="campaignrun",
            name="operation",
            field=models.CharField(
                choices=[
                    ("initial", "Initial outreach"),
                    ("followup", "Follow-up outreach"),
                    ("reply_scan", "Reply scan"),
                ],
                default="initial",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="campaignrun",
            name="triggered_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="campaign_runs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="send_claimed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="send_claimed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="claimed_clients",
                to="outreach.campaignrun",
            ),
        ),
        migrations.AddField(
            model_name="emailreply",
            name="client_company",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="emailreply",
            name="client_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="outreachcampaign",
            name="subject_template",
            field=models.CharField(
                default="180DC IIT Kharagpur X {{company}}",
                help_text="Use the same placeholders as the body template.",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="actionlog",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="action_logs",
                to="outreach.client",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="linkedin_url",
            field=models.URLField(
                blank=True,
                validators=[
                    django.core.validators.URLValidator(schemes=["http", "https"])
                ],
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="status",
            field=models.CharField(
                choices=[
                    ("Not Contacted", "Not Contacted"),
                    ("Sending", "Sending"),
                    ("Pinged", "Pinged"),
                    ("Replied", "Replied"),
                    ("Follow Up", "Follow Up"),
                    ("Meeting Set", "Meeting Set"),
                    ("Rejected", "Rejected"),
                ],
                default="Not Contacted",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="website",
            field=models.URLField(
                blank=True,
                validators=[
                    django.core.validators.URLValidator(schemes=["http", "https"])
                ],
            ),
        ),
        migrations.AlterField(
            model_name="emailreply",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replies",
                to="outreach.client",
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="mailbox_app_password",
            field=outreach.fields.EncryptedTextField(
                blank=True,
                help_text="App password or mailbox password used for SMTP/IMAP.",
            ),
        ),
        migrations.CreateModel(
            name="OutboundEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_company", models.CharField(blank=True, max_length=255)),
                ("client_email", models.EmailField(blank=True, max_length=254)),
                ("recipient", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=998)),
                ("body", models.TextField()),
                ("message_id", models.CharField(max_length=500, unique=True)),
                (
                    "generation_mode",
                    models.CharField(
                        choices=[
                            ("ai", "Gemini AI"),
                            ("campaign_template", "Campaign template"),
                            ("static_template", "Built-in template"),
                        ],
                        max_length=30,
                    ),
                ),
                ("generation_error", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("unknown", "Delivery unknown"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "followup_number",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("idempotency_key", models.CharField(max_length=255, unique=True)),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outbound_emails",
                        to="outreach.outreachcampaign",
                    ),
                ),
                (
                    "campaign_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outbound_emails",
                        to="outreach.campaignrun",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outbound_emails",
                        to="outreach.client",
                    ),
                ),
                (
                    "team_member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outbound_emails",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="actionlog",
            name="outbound_email",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="action_logs",
                to="outreach.outboundemail",
            ),
        ),
        migrations.AddField(
            model_name="emailreply",
            name="outbound_email",
            field=models.ForeignKey(
                blank=True,
                help_text="Outgoing message this reply belongs to, when known.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replies",
                to="outreach.outboundemail",
            ),
        ),
        migrations.AddIndex(
            model_name="outboundemail",
            index=models.Index(
                fields=["recipient", "-created_at"],
                name="outreach_ou_recipie_745031_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="outboundemail",
            index=models.Index(
                fields=["status", "created_at"], name="outreach_ou_status_2f9da4_idx"
            ),
        ),
        migrations.RunPython(
            populate_audit_snapshots_and_encrypt_credentials,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
