# Generated by Django 6.0.3 on 2026-08-19 11:35

import outreach.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outreach", "0008_teammember_mailbox_app_password_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FollowupRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("total", models.PositiveIntegerField(default=0)),
                ("processed", models.PositiveIntegerField(default=0)),
                ("sent", models.PositiveIntegerField(default=0)),
                ("failed", models.PositiveIntegerField(default=0)),
                ("current_company", models.CharField(blank=True, max_length=255)),
                ("current_step", models.CharField(blank=True, max_length=50)),
                ("log", models.JSONField(blank=True, default=list)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-started_at"],
                "abstract": False,
            },
            bases=(outreach.models.RunLogStatsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ScanRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("total", models.PositiveIntegerField(default=0)),
                ("processed", models.PositiveIntegerField(default=0)),
                ("sent", models.PositiveIntegerField(default=0)),
                ("failed", models.PositiveIntegerField(default=0)),
                ("current_company", models.CharField(blank=True, max_length=255)),
                ("current_step", models.CharField(blank=True, max_length=50)),
                ("log", models.JSONField(blank=True, default=list)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-started_at"],
                "abstract": False,
            },
            bases=(outreach.models.RunLogStatsMixin, models.Model),
        ),
        migrations.AddField(
            model_name="actionlog",
            name="ai_failure_reason",
            field=models.CharField(
                blank=True,
                help_text="Why Gemini generation fell back, if it did.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="actionlog",
            name="ai_used",
            field=models.BooleanField(
                default=False,
                help_text="Whether Gemini generated this email (False = static fallback template).",
            ),
        ),
        migrations.AddField(
            model_name="actionlog",
            name="email_body",
            field=models.TextField(
                blank=True,
                help_text="Full body of the email actually sent, for audit/debugging.",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="status",
            field=models.CharField(
                choices=[
                    ("Not Contacted", "Not Contacted"),
                    ("Sending", "Sending"),
                    ("Pinged", "Pinged"),
                    ("Replied", "Replied"),
                    ("Follow Up", "Follow Up"),
                    ("Meeting Set", "Meeting Set"),
                    ("Rejected", "Rejected"),
                ],
                default="Not Contacted",
                max_length=20,
            ),
        ),
    ]
