# Generated by Django 6.0.3 on 2026-09-01 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outreach", "0009_reliability_security_audit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outboundemail",
            name="generation_mode",
            field=models.CharField(
                choices=[
                    ("ai", "Gemini AI"),
                    ("campaign_template", "Campaign template"),
                    ("static_template", "Built-in template"),
                    ("failed", "Generation failed"),
                ],
                max_length=30,
            ),
        ),
    ]
