# Generated by Django 6.0.3 on 2026-08-19 11:37

import outreach.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("outreach", "0009_followuprun_scanrun_actionlog_ai_failure_reason_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teammember",
            name="mailbox_app_password",
            field=outreach.fields.EncryptedCharField(
                blank=True,
                help_text="App password or mailbox password used for SMTP/IMAP (encrypted at rest).",
                max_length=512,
            ),
        ),
    ]
