# Generated by Django 6.0.3 on 2026-08-21 13:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outreach", "0011_encrypt_existing_mailbox_passwords"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyResearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_key",
                    models.CharField(
                        db_index=True,
                        help_text="Normalised company name used as the cache key.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("summary", models.TextField(blank=True)),
                (
                    "grounded",
                    models.BooleanField(
                        default=False,
                        help_text="False when the search returned nothing — the email will be generic.",
                    ),
                ),
                (
                    "hit_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Times this cached entry was reused instead of re-searching.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "refreshed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name_plural": "Company research",
                "ordering": ["company_name"],
            },
        ),
        migrations.AddField(
            model_name="actionlog",
            name="quality_issues",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Content-quality defects detected in the sent email.",
            ),
        ),
        migrations.AddField(
            model_name="actionlog",
            name="quality_score",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="0-100 content-quality score of the email that was sent (see quality.py).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="actionlog",
            name="research_grounded",
            field=models.BooleanField(
                default=False,
                help_text="A live Google-Search research summary was available when this email was written.",
            ),
        ),
        migrations.AddField(
            model_name="actionlog",
            name="was_repaired",
            field=models.BooleanField(
                default=False,
                help_text="The first AI draft failed the quality gate and a repair pass fixed it.",
            ),
        ),
    ]
